### ISSUE TITLE
Create CONTRIBUTING.md to give some instructions

### ISSUE THREAD

**Issue by caian-gums** [FrankKair/polyglot-euler#14]
It would be a nice idea if this project has a `CONTRIBUTING.md` file to guide some newcomers (as me 😁 )

I think on something about this topics:
* Structure of PR naming
* Structure of branch naming (maybe too much?)
* Structure of commit messages in order to create some log of what problems and what language it was solved
* On each PR, create some description to describe your way of thinking (as example, I posted on [page 9](https://projecteuler.net/thread=1;page=9) on Project Euler forum as user caiangums)

Can we discuss about this?

**Comment by caian-gums** [comment]
I also added a description to my PR that can be used as a template or example #13

**Comment by FrankKair** [comment]
Good idea, @caian-gums!
We should definitely think about something like that to give more structure and consistency to the project. I liked your ideas! What about something like this for a pull request template?


### How the solution works
Explain the reasoning behind your solution.

### Performance
Use `$ time` to show us how performant the code is.


In the `CONTRIBUTING.md` file we could also give some guidelines for the programming languages. Like `pythonic` code for Python, using `go fmt` for Go, using `Rubocop` for Ruby...

**Comment by fredericojordan** [comment]
Couldn't we use the problem's README to document these things? Maybe have a "Solutions" segment with a quick description of what the algorithm does?

**Comment by fredericojordan** [comment]
Or maybe use the project's wiki? I just think closed PRs tend to never be seen again...

**Comment by caian-gums** [comment]
I think that wiki can be a better place to store that kind of information as @fredericojordan said. We can keep the PR guideline but we can have the Wiki as a better place to discuss general optimizations and other stuff.

As a suggestion, I can start writing about Fibonacci and @FrankKair can help too as I know that your solution in Python is different than mine in C++, and we can link the implementations of each part of the wiki.

**Comment by FrankKair** [comment]
@fredericojordan @caian-gums I just opened the wiki with a simple welcome message. What's the structure that you guys suggest?

I'll create a `contributing.md` as well, with the guidelines for solving the problems, such as striving for performance and how to structure modules in languages like Erlang, Elixir or how to use the main in languages link C++, Rust and Go.

**Comment by fredericojordan** [comment]
The wiki looks nice, but I think you need to open up permissions! 😄

**Comment by FrankKair** [comment]
@fredericojordan I couldn't find any permissions stuff, so I added you and @caian-gums as collaborators, and with these credentials, I think you can also edit the wiki pages. Can you test it to make sure it's working?

**Comment by fredericojordan** [comment]
Yep! Seems to be working fine! I'll add some sample pages and we can discuss them, how about that?

**Comment by FrankKair** [comment]
Awesome!

**Comment by FrankKair** [comment]
It looks awesome, @fredericojordan! Very well explained 👏🏼

**Comment by FrankKair** [comment]
I think #50 and #61 close this issue 😊✅
