### ISSUE TITLE
REPL links for easy testing

### ISSUE THREAD

**Issue by fredericojordan** [FrankKair/polyglot-euler#18]
How do you guys feel towards adding some [REPL.it](https://repl.it/) links on each problem's description?

For those who aren't familiar with it, it provides an online REPL for most popular languages (Elixir not included 😒), with the option of storing code with a permalink ([example](https://repl.it/@FredericoJordan/ProjectEuler001Cpp)).

This functionality would provide an easy and quick platform for testing/debugging/optimization purposes without the hassle of having to set up the language environment.

One of the only downsides I can think of is having to update these snippet links whenever we make changes to our solutions. I don't know if there's a way of loading the code from this repo every time the link is loaded, but that would neatly solve this problem.

**Comment by fredericojordan** [comment]
@FrankKair 🙃

**Comment by fredericojordan** [comment]
We could also use [Try it online!](https://tio.run/##dZHBTsMwDIbvfgqjCSlVNakTKpd0u0@CGy9QpelwlKZVk8AB9dlLQlpg0PkS57f/z3IihmF/EWKed2SE9o3EinrrRll3J/CWzAVN3Uk71EKidQ0H2DWyJSPx6fx8fsFDURQAZBzaXr9JluEHYIiojNJ67fCIJf/S2n5EFgsUtAcejipRYpof8XE1rwAV@oh/S@@vpCUytdp@t8dY5gWS4lcFapHdBd89ltlf07WRqX2Z8X8NEaAwx/LW6C1SvkWa4PYtrhuWq/Dw40sdE0CiOz@aZQiHKT18V5PZfvflSxJN9N5F@FINmTSNDpR5/gQ), which seem to have a wider support, and also has timing stats built-in!

**Comment by caian-gums** [comment]
I think it's a nice feature to test the code posted here. I don't know about optimizations and how it can be achieved but seems a really good feature to someone that doesn't know how to set up the proper environment for Rust or Elixir.

👍

**Comment by fredericojordan** [comment]
It facilitates optimization in the sense that you can quickly test different implementations (and even time the computation) with little overhead.

**Comment by fredericojordan** [comment]
Or we could at least use them on PRs, as in #20.

**Comment by fredericojordan** [comment]
[Try it online](https://tio.run/) has the advantage of encoding the whole program on the URI (I think), which facilitates it's maintenance, IMO.

**Comment by FrankKair** [comment]
That's a very nice idea, @fredericojordan! 
I'll add this to the pull request template 😊

**Comment by FrankKair** [comment]
Done -> https://github.com/FrankKair/polyglot-euler/blob/master/.github/pull_request_template.md
